### ISSUE TITLE
Issues, that are relevant and part of the pullrequest, are getting filtered out

### ISSUE THREAD

**Issue by janniksam** [cake-contrib/Cake.Issues.PullRequests.AzureDevOps#164]
I am trying to make this work on a Azure Devops Server (on-premise, not in cloud).

I got 107 warnings. One of them is:

> ##[warning]**src/core/servicebase/HeaderReader**.cs(11,1): warning : Name 'c_Bla' does not match rule 'Constant fields (private)'. Suggested name is 'C_BLA'.

But unfortunately it 

> Processing 107 new issues
> Fetching existing threads and comments...
> 107 issue(s) were filtered because they do not belong to files that were changed in this pull request
> All issues were filtered. Nothing new to post.

I did add it in one of the commits of the pullrequest:

![Commit in PR](https://user-images.githubusercontent.com/15337798/79562306-206d0500-80ab-11ea-842b-15baa38b0577.png)

What could be wrong?
Is there any way to get more info? What can I do?

**Comment by pascalberger** [comment]
You can run your build script with diagnostic logging (`--verbosity diagnostic`) and it will output detailed information. If you are able to post the relevant output of the diagnostic output here it would help to determine what it exactly does.

**Comment by pascalberger** [comment]
Just saw from the information you provided that one possible solution could be casing: Warning is for `src/core/servicebase/HeaderReader.cs` while the actual file path is `Src/Core/ServiceBase/HeaderReader.cs`.

**Comment by janniksam** [comment]
I see it aswell, but I have no  idea how to fix that.

When I look at the Resharper Inspect Code result (the xml-file) everything is in lower case. No idea, if there is a way to fix that...

**Comment by janniksam** [comment]
Well, it has to be the solution file. It is generated during build and adds every project file in lowercase. Let me try to fix that.

**Comment by pascalberger** [comment]
Other possibility would be to add an additional property to [ReportIssuesToPullRequestSettings](https://cakeissues.net/api/Cake.Issues.PullRequests/ReportIssuesToPullRequestSettings/) to make the comparison case-insenstive if this would solve your use case, or are you on a case-sensitive OS?

**Comment by janniksam** [comment]
(I already wrote comment his afternoon, but somehow it save...)

I didn't like like the second approach, because it would be fixing a "consequential bug", atleast it feels like it for me.

It took me way too long to fix the casing issue in my solution generation, but I got it working now. 👍 

Do you by any chance know why the warnings on the "Log" tab of the build is capped to 10, even if I have like a hundred warnings? The summary page on the other hand shows me a 100 warnings during build. Thats the only thing for me that still looks weird.

**Comment by pascalberger** [comment]
> Do you by any chance know why the warnings on the "Log" tab of the build is capped to 10, even if I have like a hundred warnings? The summary page on the other hand shows me a 100 warnings during build. Thats the only thing for me that still looks weird.

I think this is by design on Azure DevOps. See this [Developer Community entry](https://developercommunity.visualstudio.com/content/problem/187596/only-11-issues-displayed-in-release-summary.html)
