### ISSUE TITLE
Add new custom property for the property type.

### ISSUE THREAD

**Issue by janniksam** [cake-contrib/Cake.Issues.PullRequests.AzureDevOps#182]
To allow us to filter by provider type later on, we'll have save and read the provider type from the created pullrequest threads.

1. We should add a new property `ProviderType` to a `AzureDevOpsPullRequestCommentThread` (already in progress in the Cake.Issues.PullRequest addin)

2. This addin should write the Provider type of each issue to a custom property (like it's already been done for `CommentSource`)

3. When we read all existing threads, this addin should read the custom property and set the value `AzureDevOpsPullRequestCommentThread.ProviderType`.

**Comment by pascalberger** [comment]
Logic for filtering issues should be implemented in Cake.Issues.PullRequests. [IPullRequestDiscussionThread](https://github.com/cake-contrib/Cake.Issues.PullRequests/blob/develop/src/Cake.Issues.PullRequests/IPullRequestDiscussionThread.cs) needs to be enhanced first with a property to hold the provider type. 
Afterwards it can be implemented here like you described by storing a custom property.
